name: Deploy Automatizado Local

# 1. Gatilho: Dispara quando houver um push na main
on:
  push:
    branches: [main]

jobs:
  deploy:
    # 2. Manda rodar no seu computador (onde o Runner está ativo)
    runs-on: self-hosted

    steps:
      - name: Baixar codigo atualizado
        uses: actions/checkout@v4

      - name: Reconstruir imagem do C# e reiniciar container
        run: |
          docker compose build minha-app-mvc
          docker compose up -d --no-deps minha-app-mvc
